// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: p1WZMrq9so6Bp66aQvBH7F
// Component: ExCoMKwQvtzW
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: p1WZMrq9so6Bp66aQvBH7F/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: ExCoMKwQvtzW/css
import Rectangle5Icon from "./icons/PlasmicIcon__Rectangle5"; // plasmic-import: 0HDjvMxcrt/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"top"}
            data-plasmic-override={overrides.top}
            className={classNames(defaultcss.all, sty.top)}
          >
            <div
              data-plasmic-name={"bg"}
              data-plasmic-override={overrides.bg}
              className={classNames(defaultcss.all, sty.bg)}
            >
              <div
                data-plasmic-name={"rectangle"}
                data-plasmic-override={overrides.rectangle}
                className={classNames(defaultcss.all, sty.rectangle)}
              />

              <div
                data-plasmic-name={"design"}
                data-plasmic-override={overrides.design}
                className={classNames(defaultcss.all, sty.design)}
              >
                <div
                  data-plasmic-name={"_01"}
                  data-plasmic-override={overrides._01}
                  className={classNames(defaultcss.all, sty._01)}
                >
                  <div
                    data-plasmic-name={"shadow"}
                    data-plasmic-override={overrides.shadow}
                    className={classNames(defaultcss.all, sty.shadow)}
                  />

                  <Rectangle5Icon
                    className={classNames(defaultcss.all, sty.svg__sUrqn)}
                    role={"img"}
                  />
                </div>

                <div
                  data-plasmic-name={"_02"}
                  data-plasmic-override={overrides._02}
                  className={classNames(defaultcss.all, sty._02)}
                >
                  <div
                    data-plasmic-name={"shadow2"}
                    data-plasmic-override={overrides.shadow2}
                    className={classNames(defaultcss.all, sty.shadow2)}
                  />

                  <div
                    data-plasmic-name={"rectangle5Copy"}
                    data-plasmic-override={overrides.rectangle5Copy}
                    className={classNames(defaultcss.all, sty.rectangle5Copy)}
                  />
                </div>

                <div
                  data-plasmic-name={"_03"}
                  data-plasmic-override={overrides._03}
                  className={classNames(defaultcss.all, sty._03)}
                >
                  <div
                    data-plasmic-name={"shadow3"}
                    data-plasmic-override={overrides.shadow3}
                    className={classNames(defaultcss.all, sty.shadow3)}
                  />

                  <Rectangle5Icon
                    className={classNames(defaultcss.all, sty.svg__piEts)}
                    role={"img"}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"colorfulShapes"}
                data-plasmic-override={overrides.colorfulShapes}
                className={classNames(defaultcss.all, sty.colorfulShapes)}
              />
            </div>

            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(defaultcss.all, sty.logo)}
            >
              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(defaultcss.all, sty.rectangle4)}
              />

              <div
                data-plasmic-name={"rectangle4Copy"}
                data-plasmic-override={overrides.rectangle4Copy}
                className={classNames(defaultcss.all, sty.rectangle4Copy)}
              />

              <div
                data-plasmic-name={"contrastDesignStud"}
                data-plasmic-override={overrides.contrastDesignStud}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.contrastDesignStud
                )}
              >
                {"CONTRAST \nDesign Studio"}
              </div>
            </div>

            <div
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              className={classNames(defaultcss.all, sty.navBar)}
            >
              <div
                data-plasmic-name={"hover"}
                data-plasmic-override={overrides.hover}
                className={classNames(defaultcss.all, sty.hover)}
              />

              <div
                data-plasmic-name={"homeFeaturesPricin"}
                data-plasmic-override={overrides.homeFeaturesPricin}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.homeFeaturesPricin
                )}
              >
                {
                  "Home          Features          Pricing          Blog          Contact"
                }
              </div>
            </div>

            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(defaultcss.all, sty.text)}
            >
              <div
                data-plasmic-name={"manageYourWholeBu"}
                data-plasmic-override={overrides.manageYourWholeBu}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.manageYourWholeBu
                )}
              >
                {
                  "Manage your whole Business from one device\nEasily, Affordably"
                }
              </div>

              <div
                data-plasmic-name={"yourText"}
                data-plasmic-override={overrides.yourText}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.yourText
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis  laboris nisi ut aliquip ex ea commodo consequat."
                }
              </div>
            </div>

            <div
              data-plasmic-name={"buttons"}
              data-plasmic-override={overrides.buttons}
              className={classNames(defaultcss.all, sty.buttons)}
            >
              <div
                data-plasmic-name={"getStartedBtn"}
                data-plasmic-override={overrides.getStartedBtn}
                className={classNames(defaultcss.all, sty.getStartedBtn)}
              >
                <div
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(defaultcss.all, sty.rectangle2)}
                />

                <div
                  data-plasmic-name={"box"}
                  data-plasmic-override={overrides.box}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box
                  )}
                >
                  {"Get Started"}
                </div>
              </div>

              <div
                data-plasmic-name={"watchPromoBtn"}
                data-plasmic-override={overrides.watchPromoBtn}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.watchPromoBtn
                )}
              >
                {" Watch the Promo Video"}
              </div>
            </div>

            <div
              data-plasmic-name={"appScreen"}
              data-plasmic-override={overrides.appScreen}
              className={classNames(defaultcss.all, sty.appScreen)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "top",
    "bg",
    "rectangle",
    "design",
    "_01",
    "shadow",
    "_02",
    "shadow2",
    "rectangle5Copy",
    "_03",
    "shadow3",
    "colorfulShapes",
    "logo",
    "rectangle4",
    "rectangle4Copy",
    "contrastDesignStud",
    "navBar",
    "hover",
    "homeFeaturesPricin",
    "text",
    "manageYourWholeBu",
    "yourText",
    "buttons",
    "getStartedBtn",
    "rectangle2",
    "box",
    "watchPromoBtn",
    "appScreen"
  ],

  top: [
    "top",
    "bg",
    "rectangle",
    "design",
    "_01",
    "shadow",
    "_02",
    "shadow2",
    "rectangle5Copy",
    "_03",
    "shadow3",
    "colorfulShapes",
    "logo",
    "rectangle4",
    "rectangle4Copy",
    "contrastDesignStud",
    "navBar",
    "hover",
    "homeFeaturesPricin",
    "text",
    "manageYourWholeBu",
    "yourText",
    "buttons",
    "getStartedBtn",
    "rectangle2",
    "box",
    "watchPromoBtn",
    "appScreen"
  ],

  bg: [
    "bg",
    "rectangle",
    "design",
    "_01",
    "shadow",
    "_02",
    "shadow2",
    "rectangle5Copy",
    "_03",
    "shadow3",
    "colorfulShapes"
  ],

  rectangle: ["rectangle"],
  design: [
    "design",
    "_01",
    "shadow",
    "_02",
    "shadow2",
    "rectangle5Copy",
    "_03",
    "shadow3"
  ],

  _01: ["_01", "shadow"],
  shadow: ["shadow"],
  _02: ["_02", "shadow2", "rectangle5Copy"],
  shadow2: ["shadow2"],
  rectangle5Copy: ["rectangle5Copy"],
  _03: ["_03", "shadow3"],
  shadow3: ["shadow3"],
  colorfulShapes: ["colorfulShapes"],
  logo: ["logo", "rectangle4", "rectangle4Copy", "contrastDesignStud"],
  rectangle4: ["rectangle4"],
  rectangle4Copy: ["rectangle4Copy"],
  contrastDesignStud: ["contrastDesignStud"],
  navBar: ["navBar", "hover", "homeFeaturesPricin"],
  hover: ["hover"],
  homeFeaturesPricin: ["homeFeaturesPricin"],
  text: ["text", "manageYourWholeBu", "yourText"],
  manageYourWholeBu: ["manageYourWholeBu"],
  yourText: ["yourText"],
  buttons: ["buttons", "getStartedBtn", "rectangle2", "box", "watchPromoBtn"],
  getStartedBtn: ["getStartedBtn", "rectangle2", "box"],
  rectangle2: ["rectangle2"],
  box: ["box"],
  watchPromoBtn: ["watchPromoBtn"],
  appScreen: ["appScreen"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    top: makeNodeComponent("top"),
    bg: makeNodeComponent("bg"),
    rectangle: makeNodeComponent("rectangle"),
    design: makeNodeComponent("design"),
    _01: makeNodeComponent("_01"),
    shadow: makeNodeComponent("shadow"),
    _02: makeNodeComponent("_02"),
    shadow2: makeNodeComponent("shadow2"),
    rectangle5Copy: makeNodeComponent("rectangle5Copy"),
    _03: makeNodeComponent("_03"),
    shadow3: makeNodeComponent("shadow3"),
    colorfulShapes: makeNodeComponent("colorfulShapes"),
    logo: makeNodeComponent("logo"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle4Copy: makeNodeComponent("rectangle4Copy"),
    contrastDesignStud: makeNodeComponent("contrastDesignStud"),
    navBar: makeNodeComponent("navBar"),
    hover: makeNodeComponent("hover"),
    homeFeaturesPricin: makeNodeComponent("homeFeaturesPricin"),
    text: makeNodeComponent("text"),
    manageYourWholeBu: makeNodeComponent("manageYourWholeBu"),
    yourText: makeNodeComponent("yourText"),
    buttons: makeNodeComponent("buttons"),
    getStartedBtn: makeNodeComponent("getStartedBtn"),
    rectangle2: makeNodeComponent("rectangle2"),
    box: makeNodeComponent("box"),
    watchPromoBtn: makeNodeComponent("watchPromoBtn"),
    appScreen: makeNodeComponent("appScreen"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
